---
title: "R Notebook"
output: html_notebook
---
```{r Importing libraries}
library(dplyr)
library(tidyr)
library(zoo)
library(crqa)
library(nonlinearTseries)
``` 
```{r Load Datasets}
left_df_1 <- read.csv(".\\OpenPose\\1\\left_dataframe.csv")
right_df_1 <- read.csv(".\\OpenPose\\1\\right_dataframe.csv")
left_df_2 <- read.csv(".\\OpenPose\\2\\left_dataframe.csv")
right_df_2 <- read.csv(".\\OpenPose\\2\\right_dataframe.csv")
right_df_S1 <- read.csv(".\\OpenPose\\S1\\right_dataframe.csv")
left_df_S1 <- read.csv(".\\OpenPose\\S1\\left_dataframe.csv")
index <- seq(1:196)
index2 <- seq(1:74)
indexS1 <- seq(1:275)
```

For the shoulder adjustments, we want a time series variable that is the per person per shoulder change in y
```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left2
y_LS_left <- left_df_1$LShoulder
y_LS_left <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left))
#Missing Data
mean(complete.cases(y_LS_left))
na.locf(y_LS_left)
y_LS_left <- 720-y_LS_left
plot(index, y_LS_left)
```
```{r}
y_RS_left <- left_df_1$RShoulder
y_RS_left <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_left))
#Missing Data
mean(complete.cases(y_RS_left))
na.locf(y_RS_left)
y_RS_left <- 720-y_RS_left
plot(index, y_RS_left)
```

```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left
y_LS_right <- right_df_1$LShoulder
y_LS_right <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_right))
#Missing Data
mean(complete.cases(y_LS_right))
na.locf(y_LS_right)
y_LS_right <- 720-y_LS_right
plot(index, y_LS_right)
```
```{r}
y_RS_right <- right_df_1$RShoulder
y_RS_right <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_right))
#Missing Data
mean(complete.cases(y_RS_right))
na.locf(y_RS_right)
y_RS_right <- 720-y_RS_right
plot(index, y_RS_right)
```
```{r}
ccf(y_LS_right, y_LS_left, lag = 64)
```
```{r}
ccf(y_RS_right, y_RS_left, lag = 64)
```

Same for the second dataset
```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left
y_LS_left2 <- left_df_2$LShoulder
y_LS_left2 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left2))
#Missing Data
mean(complete.cases(y_LS_left2))
na.locf(y_LS_left2)
y_LS_left2 <- 720-y_LS_left2
plot(index2, y_LS_left2)
```
```{r}
y_RS_left2 <- left_df_2$RShoulder
y_RS_left2 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_left2))
#Missing Data
mean(complete.cases(y_RS_left2))
na.locf(y_RS_left2)
y_RS_left2 <- 720-y_RS_left2
plot(index2, y_RS_left2)
```
```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left
y_LS_right2 <- left_df_2$LShoulder
y_LS_right2 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_right2))
#Missing Data
mean(complete.cases(y_LS_right2))
na.locf(y_LS_right2)
y_LS_right2 <- 720-y_LS_right2
plot(index2, y_LS_right2)
```
```{r}
y_RS_right2 <- right_df_2$RShoulder
y_RS_right2 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_right2))
#Missing Data
mean(complete.cases(y_RS_right2))
na.locf(y_RS_right2)
y_RS_right2 <- 720-y_RS_right2
plot(index2, y_RS_right2)
```

```{r}
ccf(y_LS_right2, y_LS_left2, lag = 64)
```
```{r}
ccf(y_RS_right2, y_RS_left2, lag = 64)
```

Now for sample 1
```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left
y_LS_leftS1 <- left_df_S1$LShoulder
y_LS_leftS1 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_leftS1))
#Missing Data
mean(complete.cases(y_LS_leftS1))
na.locf(y_LS_leftS1)
y_LS_leftS1 <- 720-y_LS_leftS1
plot(indexS1, y_LS_leftS1)
```
```{r}
y_RS_leftS1 <- left_df_S1$RShoulder
y_RS_leftS1 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_leftS1))
#Missing Data
mean(complete.cases(y_RS_leftS1))
na.locf(y_RS_leftS1)
y_RS_leftS1 <- 720-y_RS_leftS1
plot(indexS1, y_RS_leftS1)
```
```{r}
#for x
#for y  gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_left
y_LS_rightS1 <- right_df_S1$LShoulder
y_LS_rightS1 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_LS_rightS1))
#Missing Data
mean(complete.cases(y_LS_rightS1))
na.locf(y_LS_rightS1)
y_LS_rightS1 <- 720-y_LS_rightS1
plot(indexS1, y_LS_rightS1)
```
```{r}
y_RS_rightS1 <- right_df_S1$RShoulder
y_RS_rightS1 <- as.numeric(gsub(".*[ ]([^,]+)[)].*", "\\1", y_RS_rightS1))
#Missing Data
mean(complete.cases(y_RS_rightS1))
na.locf(y_RS_rightS1)
y_RS_rightS1 <- 720-y_RS_rightS1
plot(indexS1, y_RS_rightS1)
```

```{r}
ccf(y_LS_rightS1, y_LS_leftS1, lag = 64)
```
```{r}
ccf(y_RS_rightS1, y_RS_leftS1, lag = 64)
```

Cross Recurrence Analysis
Average Mutual Information
```{r}
mutualInformation(y_LS_left)
```
```{r}
mutualInformation(y_LS_right)
```
```{r}
mutualInformation(y_LS_left2)
```
```{r}
mutualInformation(y_LS_right2)
```
```{r}
mutualInformation(y_LS_leftS1)
```
```{r}
mutualInformation(y_LS_rightS1)
```
Recurrence Plot/Diagonal Recurrence Plot
```{r}
res = drpfromts(y_LS_right, y_LS_left , windowsize = 100, radius = 5, delay = 1, embed = 1, rescale = 0,  normalize = 0, mindiagline = 2, minvertline = 2,            tw = 0, whiteline = FALSE, recpt = FALSE,                 side = 'both', method = 'crqa', metric = 'euclidean', datatype = 'continuous')

# Save out profile for plotting
profile = res$profile

``` 
```{r}
plot(-100:100, profile, type = "l", lwd = 2, xlab = "Lag", ylab = "%REC")
```